<?php
$company = $brand['company'] ?? null;
$brandSettings = $brand['settings'] ?? [];
$companyName = $company['name'] ?? ($appName ?? config('app.name'));
$companyCode = $company['code'] ?? '';
$accent = preg_match('/^#[0-9a-f]{6}$/i', (string)($brandSettings['login_accent'] ?? '')) ? $brandSettings['login_accent'] : '#4f46e5';
$tagline = $brandSettings['login_tagline'] ?? 'People operations, without the busywork.';
?>
<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= e($title ?? 'Sign In') ?> — <?= e($companyName) ?></title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="<?= asset('css/app.css') ?>" rel="stylesheet"><link href="<?= asset('css/product-enhancements.css') ?>" rel="stylesheet"><link href="<?= asset('css/saas-theme.css') ?>" rel="stylesheet"><link href="<?= asset('css/approved-theme.css') ?>" rel="stylesheet">
</head><body class="auth-page auth-page-rich" style="--login-accent:<?= e($accent) ?>"><main class="login-shell">
<section class="login-story" aria-label="Company welcome"><div class="login-story-grid"></div><div class="login-story-content"><div class="login-company-mark"><?php if(!empty($company['logo'])): ?><img src="<?= e($company['logo']) ?>" alt="<?= e($companyName) ?> logo"><?php else: ?><img class="product-brand-mark" src="<?= asset('images/diglip-logo.png') ?>" alt="Diglip" style="max-width:80px;object-fit:contain"><?php endif; ?></div><p class="login-eyebrow">WELCOME TO <?= e(strtoupper($companyName)) ?></p><h1><?= e($tagline) ?></h1><p class="login-story-copy">Attendance, leave, payroll, documents, and conversations—connected in one secure workspace.</p><div class="login-proof"><span><i data-lucide="shield-check"></i> Company-scoped access</span><span><i data-lucide="clock-3"></i> Real-time self service</span></div></div><div class="login-story-footer">Secure employee workspace</div></section>
<section class="login-form-pane"><div class="login-form-wrap motion-scale-in"><div class="d-flex align-items-center gap-3 mb-4 d-lg-none"><div class="auth-logo"><img src="<?= asset('images/diglip-logo.png') ?>" alt="Diglip" width="48" height="48" style="object-fit:contain"></div><strong><?= e($companyName) ?></strong></div><div class="mb-4"><p class="text-uppercase small fw-bold text-primary mb-2">Employee portal</p><h2 class="h3 fw-bold mb-2">Welcome back</h2><p class="text-secondary mb-0">Sign in to continue to your workspace.</p></div><?php include config('app.paths.views') . '/partials/alerts.php'; ?>
<?php if(!empty($brand['sso_enabled'])): ?><a class="btn btn-outline-primary w-100 mb-3 login-sso" href="/auth/sso?company=<?= urlencode((string)$companyCode) ?>"><i data-lucide="key-round" class="me-2"></i>Continue with company SSO</a><div class="auth-divider"><span>or use your password</span></div><?php endif; ?>
<form method="POST" action="/login" class="auth-form"><?= csrf_field() ?><input type="hidden" name="company" value="<?= e($companyCode) ?>"><div class="mb-3"><label class="form-label" for="email">Work email</label><div class="input-group input-group-lg"><span class="input-group-text bg-transparent"><i data-lucide="mail"></i></span><input type="email" class="form-control" id="email" name="email" value="<?= e(old('email')) ?>" required autofocus autocomplete="username" placeholder="you@company.com"></div></div><div class="mb-3"><div class="d-flex justify-content-between"><label class="form-label" for="password">Password</label><a href="/forgot-password" class="small">Forgot password?</a></div><div class="input-group input-group-lg"><span class="input-group-text bg-transparent"><i data-lucide="lock-keyhole"></i></span><input type="password" class="form-control" id="password" name="password" autocomplete="current-password" required placeholder="Enter your password"><button type="button" class="btn btn-soft password-toggle" data-password-toggle="password" aria-label="Show password" aria-pressed="false"><i data-lucide="eye"></i></button></div></div><label class="form-check mb-4"><input class="form-check-input" type="checkbox" name="remember" id="remember" value="1"><span class="form-check-label">Keep me signed in on this device</span></label><button type="submit" class="btn btn-primary btn-lg w-100">Sign in <i data-lucide="arrow-right" class="ms-2"></i></button></form><p class="text-center text-secondary small mt-4 mb-0">Need access? Contact your HR administrator.</p></div></section>
</main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js"></script><script src="<?= asset('js/app.js') ?>"></script><script>if(window.lucide)lucide.createIcons();</script></body></html>
