-- Mandatory, versioned employment agreement acceptance with signed document linkage.
CREATE TABLE IF NOT EXISTS `employment_agreements` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_id` BIGINT UNSIGNED NOT NULL,
  `company_id` BIGINT UNSIGNED NOT NULL,
  `user_id` BIGINT UNSIGNED DEFAULT NULL,
  `template_version` VARCHAR(50) NOT NULL,
  `template_filename` VARCHAR(255) NOT NULL,
  `template_sha256` CHAR(64) NOT NULL,
  `status` ENUM('pending','accepted') NOT NULL DEFAULT 'pending',
  `assigned_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `viewed_at` DATETIME DEFAULT NULL,
  `accepted_at` DATETIME DEFAULT NULL,
  `signer_name` VARCHAR(191) DEFAULT NULL,
  `signature_path` VARCHAR(500) DEFAULT NULL,
  `signed_document_id` BIGINT UNSIGNED DEFAULT NULL,
  `consent_text` TEXT DEFAULT NULL,
  `accepted_ip` VARCHAR(45) DEFAULT NULL,
  `accepted_user_agent` VARCHAR(500) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_employment_agreement_employee_version` (`employee_id`, `template_version`),
  KEY `idx_employment_agreements_status` (`company_id`, `status`),
  KEY `idx_employment_agreements_user` (`user_id`),
  KEY `idx_employment_agreements_document` (`signed_document_id`),
  CONSTRAINT `fk_employment_agreements_employee` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_employment_agreements_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_employment_agreements_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_employment_agreements_document` FOREIGN KEY (`signed_document_id`) REFERENCES `employee_documents` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
