<?php

declare(strict_types=1);

return [
    'name' => $_ENV['APP_NAME'] ?? 'Diglip',
    'env' => $_ENV['APP_ENV'] ?? 'production',
    'debug' => filter_var($_ENV['APP_DEBUG'] ?? false, FILTER_VALIDATE_BOOLEAN),
    'url' => rtrim($_ENV['APP_URL'] ?? 'http://localhost', '/'),
    'key' => $_ENV['APP_KEY'] ?? '',
    'timezone' => $_ENV['APP_TIMEZONE'] ?? 'UTC',
    'locale' => 'en',
    'currency' => $_ENV['CURRENCY'] ?? 'PKR',
    'date_format' => $_ENV['DATE_FORMAT'] ?? 'Y-m-d',
    'time_format' => $_ENV['TIME_FORMAT'] ?? 'H:i',
    'datetime_format' => ($_ENV['DATE_FORMAT'] ?? 'Y-m-d') . ' ' . ($_ENV['TIME_FORMAT'] ?? 'H:i'),
    'session_lifetime' => (int) ($_ENV['SESSION_LIFETIME'] ?? 120),
    'session_secure' => filter_var($_ENV['SESSION_SECURE'] ?? false, FILTER_VALIDATE_BOOLEAN),
    'remember_me_days' => (int) ($_ENV['REMEMBER_ME_DAYS'] ?? 30),
    'login_max_attempts' => (int) ($_ENV['LOGIN_MAX_ATTEMPTS'] ?? 5),
    'login_lockout_minutes' => (int) ($_ENV['LOGIN_LOCKOUT_MINUTES'] ?? 15),
    'trusted_proxies' => array_values(array_filter(array_map('trim', explode(',', (string) ($_ENV['TRUSTED_PROXIES'] ?? ''))))),
    'password_reset_max_requests_per_hour' => (int) ($_ENV['PASSWORD_RESET_MAX_REQUESTS_PER_HOUR'] ?? 5),
    'security_hsts' => filter_var($_ENV['SECURITY_HSTS'] ?? false, FILTER_VALIDATE_BOOLEAN),
    'upload_max_size' => (int) ($_ENV['UPLOAD_MAX_SIZE'] ?? 5242880),
    'attendance' => [
        'default_radius' => (int) ($_ENV['ATTENDANCE_DEFAULT_RADIUS'] ?? 100),
        'gps_accuracy_threshold' => (int) ($_ENV['ATTENDANCE_GPS_ACCURACY_THRESHOLD'] ?? 50),
        'image_retention_days' => (int) ($_ENV['ATTENDANCE_IMAGE_RETENTION_DAYS'] ?? 365),
        'location_retention_days' => (int) ($_ENV['ATTENDANCE_LOCATION_RETENTION_DAYS'] ?? 365),
    ],
    'paths' => [
        'storage' => dirname(__DIR__) . '/storage',
        'attendance_images' => dirname(__DIR__) . '/storage/attendance-images',
        'employee_documents' => dirname(__DIR__) . '/storage/employee-documents',
        'employment_agreements' => dirname(__DIR__) . '/storage/employment-agreements',
        'leave_attachments' => dirname(__DIR__) . '/storage/leave-attachments',
        'payslips' => dirname(__DIR__) . '/storage/payslips',
        'exports' => dirname(__DIR__) . '/storage/exports',
        'logs' => dirname(__DIR__) . '/storage/logs',
        'chat_attachments' => dirname(__DIR__) . '/storage/chat-attachments',
        'monitoring' => dirname(__DIR__) . '/storage/monitoring',
        'views' => dirname(__DIR__) . '/views',
    ],
    'monitoring' => [
        'default_interval_minutes' => 10,
        'allowed_intervals' => [5, 10, 15, 20, 30],
        'min_interval_minutes' => 5,
        'session_token_ttl_hours' => 16,
        'device_token_ttl_days' => 30,
        'activity_retention_days' => 90,
        'screenshot_retention_days' => 30,
        'heartbeat_retention_days' => 30,
    ],
];
