<?php

declare(strict_types=1);

/**
 * Single source of truth for primary workspaces, child tabs, breadcrumbs,
 * mobile bottom nav, and quick actions. Only existing routes are linked.
 */
return [
    'admin' => [
        'workspaces' => [
            [
                'key' => 'dashboard',
                'label' => 'Dashboard',
                'icon' => 'layout-dashboard',
                'url' => '/admin/dashboard',
                'perm' => 'dashboard.view',
                'accent' => 'purple',
                'match' => ['/admin/dashboard'],
                'children' => [],
            ],
            [
                'key' => 'approvals',
                'label' => 'Approvals',
                'icon' => 'inbox',
                'url' => '/admin/approvals',
                'perm' => 'dashboard.view',
                'accent' => 'orange',
                'match' => ['/admin/approvals', '/admin/approval-chains'],
                'children' => [
                    ['label' => 'Inbox', 'url' => '/admin/approvals', 'perm' => 'dashboard.view'],
                    ['label' => 'Approval Chains', 'url' => '/admin/approval-chains', 'perm' => 'settings.manage'],
                ],
            ],
            [
                'key' => 'chat',
                'label' => 'Team Chat',
                'icon' => 'messages-square',
                'url' => '/chat',
                'perm' => 'chat.access',
                'accent' => 'pink',
                'badge' => 'chat_unread',
                'match' => ['/chat', '/admin/chat'],
                'children' => [
                    ['label' => 'Overview', 'url' => '/chat/overview', 'perm' => 'chat.access', 'match' => 'exact'],
                    ['label' => 'Chat', 'url' => '/chat', 'perm' => 'chat.access', 'match' => 'exact'],
                    ['label' => 'DMs', 'url' => '/chat?panel=dms', 'perm' => 'chat.direct_message', 'match' => 'query'],
                    ['label' => 'Channels', 'url' => '/chat?panel=channels', 'perm' => 'chat.access', 'match' => 'query'],
                    ['label' => 'Files', 'url' => '/chat/files', 'perm' => 'chat.download_file'],
                    ['label' => 'Saved', 'url' => '/chat/saved', 'perm' => 'chat.access'],
                    ['label' => 'Mentions', 'url' => '/chat/mentions', 'perm' => 'chat.access'],
                    ['label' => 'Notifications', 'url' => '/chat/notifications', 'perm' => 'chat.access'],
                    ['label' => 'Documents', 'url' => '/chat/documents', 'perm' => 'chat.access'],
                    ['label' => 'Settings', 'url' => '/admin/chat/settings', 'perm' => 'chat.manage_settings'],
                ],
            ],
            [
                'key' => 'attendance',
                'label' => 'Attendance',
                'icon' => 'calendar-check',
                'url' => '/admin/attendance/overview',
                'perm' => 'attendance.view',
                'accent' => 'mint',
                'match' => ['/admin/attendance', '/admin/shifts', '/admin/overtime', '/admin/holidays', '/admin/week-patterns'],
                'exclude' => [],
                'children' => [
                    ['label' => 'Overview', 'url' => '/admin/attendance/overview', 'perm' => 'attendance.view', 'match' => 'exact'],
                    ['label' => 'All Attendance', 'url' => '/admin/attendance', 'perm' => 'attendance.view', 'match' => 'list'],
                    ['label' => 'Corrections', 'url' => '/admin/attendance/corrections', 'perm' => 'attendance.correct'],
                    ['label' => 'Manual Entry', 'url' => '/admin/attendance/manual', 'perm' => 'attendance.manual'],
                    ['label' => 'Archived', 'url' => '/admin/attendance/archived', 'perm' => 'attendance.view_archived'],
                    ['label' => 'Shifts', 'url' => '/admin/shifts', 'perm' => 'shifts.view'],
                    ['label' => 'Weekly Patterns', 'url' => '/admin/week-patterns', 'perm' => 'attendance.pattern.view'],
                    ['label' => 'Overtime', 'url' => '/admin/overtime', 'perm' => 'overtime.view'],
                    ['label' => 'Holidays', 'url' => '/admin/holidays', 'perm' => 'holidays.view'],
                ],
            ],
            [
                'key' => 'leave',
                'label' => 'Leave',
                'icon' => 'calendar-days',
                'url' => '/admin/leave/overview',
                'perm' => 'leave.view',
                'accent' => 'orange',
                'match' => ['/admin/leave'],
                'exclude' => [],
                'children' => [
                    ['label' => 'Overview', 'url' => '/admin/leave/overview', 'perm' => 'leave.view', 'match' => 'exact'],
                    ['label' => 'Requests', 'url' => '/admin/leave', 'perm' => 'leave.view', 'match' => 'list'],
                    ['label' => 'Pending', 'url' => '/admin/leave/pending', 'perm' => 'leave.view'],
                    ['label' => 'Approved', 'url' => '/admin/leave/approved', 'perm' => 'leave.view'],
                    ['label' => 'Archived', 'url' => '/admin/leave/archived', 'perm' => 'leave.view_archived'],
                    ['label' => 'Types', 'url' => '/admin/leave/types', 'perm' => 'leave.types'],
                    ['label' => 'Balances', 'url' => '/admin/leave/balances', 'perm' => 'leave.balances'],
                    ['label' => 'Holidays', 'url' => '/admin/leave/holidays', 'perm' => 'holidays.view'],
                ],
            ],
            [
                'key' => 'payroll',
                'label' => 'Payroll',
                'icon' => 'wallet',
                'url' => '/admin/payroll/overview',
                'perm' => 'payroll.view',
                'accent' => 'purple',
                'match' => [
                    '/admin/payroll',
                    '/admin/salary-structures',
                    '/admin/payslips',
                    '/admin/loans',
                    '/admin/advances',
                ],
                'children' => [
                    ['label' => 'Overview', 'url' => '/admin/payroll/overview', 'perm' => 'payroll.view', 'match' => 'exact'],
                    ['label' => 'Periods', 'url' => '/admin/payroll', 'perm' => 'payroll.view', 'match' => 'list'],
                    ['label' => 'Create', 'url' => '/admin/payroll/create', 'perm' => 'payroll.process'],
                    ['label' => 'Draft', 'url' => '/admin/payroll?status=draft', 'perm' => 'payroll.view', 'match' => 'query'],
                    ['label' => 'Approved', 'url' => '/admin/payroll?status=approved', 'perm' => 'payroll.view', 'match' => 'query'],
                    ['label' => 'Archived', 'url' => '/admin/payroll/archived', 'perm' => 'payroll.view_archived'],
                    ['label' => 'Salary', 'url' => '/admin/salary-structures', 'perm' => 'salary.view'],
                    ['label' => 'Payslips', 'url' => '/admin/payslips', 'perm' => 'payslips.view'],
                    ['label' => 'Loans', 'url' => '/admin/loans', 'perm' => 'loans.view'],
                    ['label' => 'Advances', 'url' => '/admin/advances', 'perm' => 'advances.view'],
                ],
            ],
            [
                'key' => 'people',
                'label' => 'People',
                'icon' => 'users',
                'url' => '/admin/employees',
                'perm' => 'employees.view',
                'accent' => 'blue',
                'match' => [
                    '/admin/employees',
                    '/admin/departments',
                    '/admin/branches',
                    '/admin/designations',
                    '/admin/companies',
                ],
                'children' => [
                    ['label' => 'Employees', 'url' => '/admin/employees', 'perm' => 'employees.view', 'match' => 'list'],
                    ['label' => 'Import Employees', 'url' => '/admin/employees/import', 'perm' => 'employees.create'],
                    ['label' => 'Departments', 'url' => '/admin/departments', 'perm' => 'departments.view'],
                    ['label' => 'Branches', 'url' => '/admin/branches', 'perm' => 'branches.view'],
                    ['label' => 'Designations', 'url' => '/admin/designations', 'perm' => 'designations.view'],
                    ['label' => 'Companies', 'url' => '/admin/companies', 'perm' => 'companies.view'],
                ],
            ],
            [
                'key' => 'monitoring',
                'label' => 'Work Monitoring',
                'icon' => 'monitor',
                'url' => '/admin/monitoring',
                'perm' => 'monitoring.access',
                'accent' => 'cyan',
                'match' => ['/admin/monitoring'],
                'children' => [
                    ['label' => 'Overview', 'url' => '/admin/monitoring', 'perm' => 'monitoring.view_overview', 'match' => 'exact'],
                    ['label' => 'Live Employees', 'url' => '/admin/monitoring/live', 'perm' => 'monitoring.view_live_employees'],
                    ['label' => 'Activity', 'url' => '/admin/monitoring/activity', 'perm' => 'monitoring.view_team_activity'],
                    ['label' => 'Website Activity', 'url' => '/admin/monitoring/web-activity', 'perm' => 'monitoring.view_site_history'],
                    ['label' => 'Website Rules', 'url' => '/admin/monitoring/site-rules', 'perm' => 'monitoring.manage_site_rules'],
                    ['label' => 'Applications', 'url' => '/admin/monitoring/applications', 'perm' => 'monitoring.view_applications'],
                    ['label' => 'Screenshots', 'url' => '/admin/monitoring/screenshots', 'perm' => 'monitoring.view_screenshots'],
                    ['label' => 'Devices', 'url' => '/admin/monitoring/devices', 'perm' => 'monitoring.manage_devices'],
                    ['label' => 'Policies', 'url' => '/admin/monitoring/policies', 'perm' => 'monitoring.manage_policies'],
                    ['label' => 'Reports', 'url' => '/admin/monitoring/reports', 'perm' => 'monitoring.view_reports'],
                    ['label' => 'Alerts', 'url' => '/admin/monitoring/alerts', 'perm' => 'monitoring.access'],
                    ['label' => 'Audit Logs', 'url' => '/admin/monitoring/audit', 'perm' => 'monitoring.view_audit_logs'],
                    ['label' => 'Disputes', 'url' => '/admin/monitoring/disputes', 'perm' => 'monitoring.review_disputes'],
                ],
            ],
            [
                'key' => 'documents',
                'label' => 'Documents',
                'icon' => 'folder-open',
                'url' => '/admin/documents',
                'perm' => 'documents.view',
                'accent' => 'cyan',
                'match' => ['/admin/documents', '/admin/assets'],
                'children' => [
                    ['label' => 'Documents', 'url' => '/admin/documents', 'perm' => 'documents.view', 'match' => 'list'],
                    ['label' => 'Assets', 'url' => '/admin/assets', 'perm' => 'assets.view'],
                ],
            ],
            [
                'key' => 'reports',
                'label' => 'Reports',
                'icon' => 'bar-chart-3',
                'url' => '/admin/reports',
                'perm' => 'reports.view',
                'accent' => 'purple',
                'match' => ['/admin/reports'],
                // Prefer workspace-specific report tabs when those workspaces own the URI;
                // still show Reports workspace when on /admin/reports index or employees report.
                'exclude' => [
                    '/admin/reports/attendance',
                    '/admin/reports/leave',
                    '/admin/reports/payroll',
                    '/admin/reports/loans',
                    '/admin/reports/documents',
                ],
                // No 'children' here on purpose: every /admin/reports/* view already
                // includes partials/report-header.php, which renders its own
                // Overview/Attendance/Leave/Payroll/Loans/Workforce/Documents tab
                // row. A non-empty children array here would make
                // partials/workspace-tabs.php render a second, near-duplicate
                // pill row (same links, "Employees" vs "Workforce" label) right
                // above it on /admin/reports and /admin/reports/employees.
                'children' => [],
            ],
            [
                'key' => 'administration',
                'label' => 'Administration',
                'icon' => 'settings',
                'url' => '/admin/settings',
                'perm' => 'settings.manage',
                'accent' => 'cyan',
                'match_any_perm' => true,
                'match' => [
                    '/admin/users',
                    '/admin/roles',
                    '/admin/audit',
                    '/admin/settings',
                    '/admin/announcements',
                    '/admin/setup',
                ],
                // Chat settings live under Team Chat tabs when chat workspace matches first
                'children' => [
                    ['label' => 'Users', 'url' => '/admin/users', 'perm' => 'roles.manage'],
                    ['label' => 'Roles', 'url' => '/admin/roles', 'perm' => 'roles.view'],
                    ['label' => 'Audit Logs', 'url' => '/admin/audit', 'perm' => 'audit.view'],
                    ['label' => 'Settings', 'url' => '/admin/settings', 'perm' => 'settings.manage'],
                    ['label' => 'Company Setup', 'url' => '/admin/setup', 'perm' => 'settings.manage'],
                    ['label' => 'Approval Chains', 'url' => '/admin/approval-chains', 'perm' => 'settings.manage'],
                    ['label' => 'Announcements', 'url' => '/admin/announcements', 'perm' => 'announcements.view'],
                    ['label' => 'Chat Settings', 'url' => '/admin/chat/settings', 'perm' => 'chat.manage_settings'],
                ],
            ],
        ],
        'quick_actions' => [
            ['label' => 'Add Employee', 'url' => '/admin/employees/create', 'perm' => 'employees.create', 'icon' => 'user-plus'],
            ['label' => 'Take Attendance', 'url' => '/admin/attendance/manual', 'perm' => 'attendance.manual', 'icon' => 'calendar-check'],
            ['label' => 'Create Payroll', 'url' => '/admin/payroll/create', 'perm' => 'payroll.process', 'icon' => 'wallet'],
            ['label' => 'Apply Leave', 'url' => '/admin/leave', 'perm' => 'leave.view', 'icon' => 'calendar-days'],
            ['label' => 'Start Chat', 'url' => '/chat', 'perm' => 'chat.access', 'icon' => 'messages-square'],
            ['label' => 'Upload Document', 'url' => '/admin/documents', 'perm' => 'documents.view', 'icon' => 'upload'],
        ],
        'mobile_nav' => [
            ['label' => 'Home', 'url' => '/admin/dashboard', 'icon' => 'home', 'perm' => 'dashboard.view', 'match' => ['/admin/dashboard']],
            ['label' => 'Chat', 'url' => '/chat', 'icon' => 'messages-square', 'perm' => 'chat.access', 'match' => ['/chat'], 'badge' => 'chat_unread'],
            ['label' => 'Search', 'url' => '#', 'icon' => 'search', 'action' => 'search', 'perm' => null],
            ['label' => 'Alerts', 'url' => '/admin/notifications', 'icon' => 'bell', 'perm' => null, 'match' => ['/admin/notifications']],
            ['label' => 'Profile', 'url' => '/change-password', 'icon' => 'user', 'perm' => null, 'match' => ['/change-password']],
        ],
    ],

    'employee' => [
        'workspaces' => [
            [
                'key' => 'dashboard',
                'label' => 'Dashboard',
                'icon' => 'layout-dashboard',
                'url' => '/employee/dashboard',
                'accent' => 'purple',
                'match' => ['/employee/dashboard'],
                'children' => [],
            ],
            [
                'key' => 'chat',
                'label' => 'Team Chat',
                'icon' => 'messages-square',
                'url' => '/chat',
                'perm' => 'chat.access',
                'accent' => 'pink',
                'badge' => 'chat_unread',
                'match' => ['/chat'],
                'children' => [
                    ['label' => 'Overview', 'url' => '/chat/overview', 'match' => 'exact'],
                    ['label' => 'Chat', 'url' => '/chat', 'match' => 'exact'],
                    ['label' => 'DMs', 'url' => '/chat?panel=dms'],
                    ['label' => 'Channels', 'url' => '/chat?panel=channels'],
                    ['label' => 'Files', 'url' => '/chat/files'],
                    ['label' => 'Saved', 'url' => '/chat/saved'],
                    ['label' => 'Mentions', 'url' => '/chat/mentions'],
                    ['label' => 'Notifications', 'url' => '/chat/notifications'],
                    ['label' => 'Documents', 'url' => '/chat/documents'],
                ],
            ],
            [
                'key' => 'attendance',
                'label' => 'Attendance',
                'icon' => 'calendar-check',
                'url' => '/employee/attendance',
                'accent' => 'mint',
                'match' => ['/employee/attendance'],
                'children' => [
                    ['label' => 'My Attendance', 'url' => '/employee/attendance', 'match' => 'exact'],
                    ['label' => 'Calendar', 'url' => '/employee/attendance/calendar'],
                    ['label' => 'Corrections', 'url' => '/employee/attendance/corrections'],
                ],
            ],
            [
                'key' => 'leave',
                'label' => 'Leave',
                'icon' => 'calendar-days',
                'url' => '/employee/leave',
                'accent' => 'orange',
                'match' => ['/employee/leave'],
                'children' => [
                    ['label' => 'My Leave', 'url' => '/employee/leave', 'match' => 'list'],
                    ['label' => 'Apply Leave', 'url' => '/employee/leave/create'],
                ],
            ],
            [
                'key' => 'payroll',
                'label' => 'Pay',
                'icon' => 'receipt',
                'url' => '/employee/payslips',
                'accent' => 'purple',
                'match' => ['/employee/payslips', '/employee/loans', '/employee/advances'],
                'children' => [
                    ['label' => 'Payslips', 'url' => '/employee/payslips'],
                    ['label' => 'Loans', 'url' => '/employee/loans'],
                    ['label' => 'Advances', 'url' => '/employee/advances'],
                ],
            ],
            [
                'key' => 'documents',
                'label' => 'Documents',
                'icon' => 'folder-open',
                'url' => '/employee/documents',
                'accent' => 'cyan',
                'match' => ['/employee/documents', '/employee/assets'],
                'children' => [
                    ['label' => 'My Documents', 'url' => '/employee/documents'],
                    ['label' => 'My Assets', 'url' => '/employee/assets'],
                ],
            ],
            [
                'key' => 'account',
                'label' => 'Account',
                'icon' => 'user',
                'url' => '/employee/profile',
                'accent' => 'blue',
                'match' => ['/employee/profile', '/employee/notifications', '/change-password'],
                'children' => [
                    ['label' => 'Profile', 'url' => '/employee/profile'],
                    ['label' => 'Notifications', 'url' => '/employee/notifications'],
                    ['label' => 'Password', 'url' => '/change-password'],
                ],
            ],
        ],
        'quick_actions' => [
            ['label' => 'Check In/Out', 'url' => '/employee/attendance', 'icon' => 'camera'],
            ['label' => 'Apply Leave', 'url' => '/employee/leave/create', 'icon' => 'calendar-days'],
            ['label' => 'Start Chat', 'url' => '/chat', 'perm' => 'chat.access', 'icon' => 'messages-square'],
            ['label' => 'My Payslips', 'url' => '/employee/payslips', 'icon' => 'receipt'],
        ],
        'mobile_nav' => [
            ['label' => 'Home', 'url' => '/employee/dashboard', 'icon' => 'home', 'match' => ['/employee/dashboard']],
            ['label' => 'Chat', 'url' => '/chat', 'icon' => 'messages-square', 'perm' => 'chat.access', 'match' => ['/chat'], 'badge' => 'chat_unread'],
            ['label' => 'Search', 'url' => '#', 'icon' => 'search', 'action' => 'search'],
            ['label' => 'Alerts', 'url' => '/employee/notifications', 'icon' => 'bell', 'match' => ['/employee/notifications']],
            ['label' => 'Profile', 'url' => '/employee/profile', 'icon' => 'user', 'match' => ['/employee/profile']],
        ],
    ],

    /** Path segments under a list root that are sibling pages, not detail IDs */
    'reserved_under' => [
        '/admin/attendance' => ['overview', 'archived', 'manual', 'corrections', 'export', 'images'],
        '/admin/leave' => ['overview', 'archived', 'pending', 'approved', 'types', 'balances', 'holidays'],
        '/admin/payroll' => ['overview', 'archived', 'create'],
        '/admin/employees' => ['create'],
        '/admin/documents' => [],
        '/admin/monitoring' => ['live', 'activity', 'web-activity', 'site-rules', 'applications', 'screenshots', 'devices', 'policies', 'alerts', 'reports', 'audit', 'disputes'],
        '/employee/leave' => ['create'],
        '/employee/attendance' => ['calendar', 'corrections'],
    ],

    'nav_discriminators' => ['status', 'scope', 'panel'],
];
