<?php

declare(strict_types=1);

return [
    'modules' => [
        'dashboard' => [
            'dashboard.view' => 'View dashboard',
        ],
        'employees' => [
            'employees.view' => 'View employees',
            'employees.create' => 'Create employees',
            'employees.update' => 'Update employees',
            'employees.delete' => 'Delete employees',
            'employees.import' => 'Import employees',
            'employees.export' => 'Export employees',
        ],
        'companies' => [
            'companies.view' => 'View companies',
            'companies.create' => 'Create companies',
            'companies.update' => 'Update companies',
            'companies.delete' => 'Delete companies',
        ],
        'branches' => [
            'branches.view' => 'View branches',
            'branches.create' => 'Create branches',
            'branches.update' => 'Update branches',
            'branches.delete' => 'Delete branches',
        ],
        'departments' => [
            'departments.view' => 'View departments',
            'departments.create' => 'Create departments',
            'departments.update' => 'Update departments',
            'departments.delete' => 'Delete departments',
        ],
        'designations' => [
            'designations.view' => 'View designations',
            'designations.create' => 'Create designations',
            'designations.update' => 'Update designations',
            'designations.delete' => 'Delete designations',
        ],
        'shifts' => [
            'shifts.view' => 'View shifts',
            'shifts.create' => 'Create shifts',
            'shifts.update' => 'Update shifts',
            'shifts.delete' => 'Delete shifts',
            'shifts.assign' => 'Assign shifts',
        ],
        'attendance' => [
            'attendance.view' => 'View attendance',
            'attendance.edit' => 'Edit attendance',
            'attendance.approve' => 'Approve attendance',
            'attendance.reject' => 'Reject attendance',
            'attendance.manual' => 'Manual attendance entry',
            'attendance.images' => 'View attendance images',
            'attendance.locations' => 'View attendance locations',
            'attendance.export' => 'Export attendance',
            'attendance.correct' => 'Correct attendance',
            'attendance.archive' => 'Archive attendance',
            'attendance.restore' => 'Restore attendance',
            'attendance.permanently_delete' => 'Permanently delete attendance',
            'attendance.view_archived' => 'View archived attendance',
            'attendance.view_history' => 'View attendance history',
            'attendance.device.view' => 'View attendance devices',
            'attendance.device.manage' => 'Manage attendance devices',
            'attendance.device.approve' => 'Approve attendance devices',
            'attendance.security.settings' => 'Manage attendance security settings',
            'attendance.report.all_employees' => 'View all-employee attendance reports',
            'attendance.report.department' => 'View department attendance reports',
            'attendance.report.branch' => 'View branch attendance reports',
            'attendance.pattern.view' => 'View weekly schedule patterns',
            'attendance.pattern.manage' => 'Create, edit and assign weekly schedule patterns',
        ],
        'leave' => [
            'leave.view' => 'View leave',
            'leave.create' => 'Create leave',
            'leave.edit' => 'Edit leave',
            'leave.approve' => 'Approve leave',
            'leave.reject' => 'Reject leave',
            'leave.extend' => 'Extend leave',
            'leave.cancel' => 'Cancel leave',
            'leave.archive' => 'Archive leave',
            'leave.restore' => 'Restore leave',
            'leave.permanently_delete' => 'Permanently delete leave',
            'leave.view_archived' => 'View archived leave',
            'leave.view_history' => 'View leave history',
            'leave.types' => 'Manage leave types',
            'leave.balances' => 'Manage leave balances',
            'leave.export' => 'Export leave',
        ],
        'holidays' => [
            'holidays.view' => 'View holidays',
            'holidays.create' => 'Create holidays',
            'holidays.update' => 'Update holidays',
            'holidays.delete' => 'Delete holidays',
        ],
        'payroll' => [
            'payroll.view' => 'View payroll',
            'payroll.create' => 'Create payroll',
            'payroll.edit' => 'Edit payroll',
            'payroll.process' => 'Process payroll',
            'payroll.recalculate' => 'Recalculate payroll',
            'payroll.approve' => 'Approve payroll',
            'payroll.lock' => 'Lock payroll',
            'payroll.reopen' => 'Reopen payroll',
            'payroll.mark_paid' => 'Mark payroll paid',
            'payroll.cancel' => 'Cancel payroll',
            'payroll.archive' => 'Archive payroll',
            'payroll.restore' => 'Restore payroll',
            'payroll.permanently_delete' => 'Permanently delete payroll',
            'payroll.view_archived' => 'View archived payroll',
            'payroll.view_history' => 'View payroll history',
            'payroll.export' => 'Export payroll',
        ],
        'salary' => [
            'salary.view' => 'View salary structures',
            'salary.manage' => 'Manage salary structures',
        ],
        'overtime' => [
            'overtime.view' => 'View overtime',
            'overtime.approve' => 'Approve overtime',
            'overtime.manage' => 'Manage overtime',
        ],
        'loans' => [
            'loans.view' => 'View loans',
            'loans.approve' => 'Approve loans',
            'loans.manage' => 'Manage loans',
        ],
        'advances' => [
            'advances.view' => 'View salary advances',
            'advances.approve' => 'Approve salary advances',
            'advances.manage' => 'Manage salary advances',
        ],
        'payslips' => [
            'payslips.view' => 'View payslips',
            'payslips.generate' => 'Generate payslips',
            'payslips.edit' => 'Edit payslips',
            'payslips.delete' => 'Delete payslips',
        ],
        'documents' => [
            'documents.view' => 'View documents',
            'documents.manage' => 'Manage documents',
        ],
        'assets' => [
            'assets.view' => 'View assets',
            'assets.manage' => 'Manage assets',
        ],
        'announcements' => [
            'announcements.view' => 'View announcements',
            'announcements.manage' => 'Manage announcements',
        ],
        'reports' => [
            'reports.view' => 'View reports',
            'reports.export' => 'Export reports',
        ],
        'roles' => [
            'roles.view' => 'View roles',
            'roles.manage' => 'Manage roles and permissions',
        ],
        'audit' => [
            'audit.view' => 'View audit logs',
        ],
        'settings' => [
            'settings.manage' => 'Manage system settings',
        ],
        'notifications' => [
            'notifications.view' => 'View notifications',
            'notifications.manage' => 'Manage notifications',
        ],
        'chat' => [
            'chat.access' => 'Access team chat',
            'chat.direct_message' => 'Send direct messages',
            'chat.create_channel' => 'Create channels',
            'chat.manage_channel' => 'Manage channels',
            'chat.join_public_channel' => 'Join public channels',
            'chat.invite_members' => 'Invite channel members',
            'chat.remove_members' => 'Remove channel members',
            'chat.post_message' => 'Post messages',
            'chat.edit_own_message' => 'Edit own messages',
            'chat.delete_own_message' => 'Delete own messages',
            'chat.delete_any_message' => 'Delete any message',
            'chat.upload_file' => 'Upload files',
            'chat.download_file' => 'Download files',
            'chat.pin_message' => 'Pin messages',
            'chat.use_mass_mentions' => 'Use mass mentions',
            'chat.view_audit_logs' => 'View chat audit logs',
            'chat.manage_settings' => 'Manage chat settings',
        ],
        'monitoring' => [
            'monitoring.access' => 'Access work monitoring',
            'monitoring.view_overview' => 'View monitoring overview',
            'monitoring.view_live_employees' => 'View live employees',
            'monitoring.view_own_activity' => 'View own activity',
            'monitoring.view_team_activity' => 'View team activity',
            'monitoring.view_all_activity' => 'View all activity',
            'monitoring.view_applications' => 'View applications',
            'monitoring.view_screenshots' => 'View screenshots',
            'monitoring.download_screenshots' => 'Download screenshots',
            'monitoring.delete_screenshots' => 'Delete screenshots',
            'monitoring.manage_devices' => 'Manage devices',
            'monitoring.manage_policies' => 'Manage policies',
            'monitoring.assign_policies' => 'Assign monitoring policies',
            'monitoring.stop_session' => 'Stop monitoring session',
            'monitoring.view_reports' => 'View monitoring reports',
            'monitoring.view_audit_logs' => 'View monitoring audit logs',
            'monitoring.view_storage' => 'View monitoring storage',
            'monitoring.enable_exceptional_recording' => 'Enable exceptional recording',
            'monitoring.view_recordings' => 'View recordings',
            'monitoring.download_recordings' => 'Download recordings',
            'monitoring.delete_recordings' => 'Delete recordings',
            'monitoring.manage_recording_policy' => 'Manage recording policy',
            'monitoring.view_recording_audit' => 'View recording audit',
        ],
    ],
    'role_defaults' => [
        'super_admin' => ['*'],
        'company_admin' => [
            'dashboard.view', 'employees.*', 'companies.view', 'companies.update',
            'branches.*', 'departments.*', 'designations.*', 'shifts.*',
            'attendance.*', 'attendance.report.all_employees', 'attendance.report.department', 'attendance.report.branch',
            'attendance.pattern.view', 'attendance.pattern.manage',
            'leave.*', 'holidays.*', 'payroll.*', 'salary.*',
            'overtime.*', 'loans.*', 'advances.*', 'payslips.*', 'documents.*',
            'assets.*', 'announcements.*', 'reports.*', 'roles.view',
            'audit.view', 'settings.manage', 'notifications.*', 'chat.*',
            'monitoring.access', 'monitoring.view_overview', 'monitoring.view_live_employees',
            'monitoring.view_team_activity', 'monitoring.view_all_activity', 'monitoring.view_applications',
            'monitoring.view_screenshots', 'monitoring.download_screenshots', 'monitoring.delete_screenshots',
            'monitoring.manage_devices', 'monitoring.manage_policies', 'monitoring.assign_policies',
            'monitoring.stop_session', 'monitoring.view_reports', 'monitoring.view_audit_logs',
            'monitoring.view_storage',
        ],
        'hr_manager' => [
            'dashboard.view', 'employees.*', 'branches.view', 'departments.view',
            'designations.view', 'shifts.*', 'attendance.*', 'attendance.report.all_employees',
            'attendance.report.department', 'attendance.report.branch',
            'attendance.pattern.view', 'attendance.pattern.manage', 'leave.*',
            'holidays.*', 'payroll.view', 'payroll.process', 'salary.view',
            'overtime.*', 'loans.view', 'loans.approve', 'advances.view',
            'advances.approve', 'payslips.*', 'documents.*', 'assets.*',
            'announcements.*', 'reports.*', 'notifications.view',
            'chat.access', 'chat.direct_message', 'chat.create_channel', 'chat.manage_channel',
            'chat.join_public_channel', 'chat.invite_members', 'chat.remove_members',
            'chat.post_message', 'chat.edit_own_message', 'chat.delete_own_message',
            'chat.delete_any_message', 'chat.upload_file', 'chat.download_file',
            'chat.pin_message', 'chat.use_mass_mentions', 'chat.view_audit_logs',
            'monitoring.access', 'monitoring.view_overview', 'monitoring.view_live_employees',
            'monitoring.view_team_activity', 'monitoring.view_all_activity', 'monitoring.view_applications',
            'monitoring.view_screenshots', 'monitoring.download_screenshots', 'monitoring.delete_screenshots',
            'monitoring.manage_devices', 'monitoring.manage_policies', 'monitoring.assign_policies',
            'monitoring.stop_session', 'monitoring.view_reports', 'monitoring.view_audit_logs',
            'monitoring.view_storage',
        ],
        'department_manager' => [
            'dashboard.view', 'employees.view', 'attendance.view', 'attendance.approve',
            'attendance.report.department',
            'leave.view', 'leave.approve', 'leave.reject', 'overtime.view',
            'overtime.approve', 'reports.view', 'announcements.view', 'notifications.view',
            'chat.access', 'chat.direct_message', 'chat.create_channel', 'chat.join_public_channel',
            'chat.invite_members', 'chat.post_message', 'chat.edit_own_message',
            'chat.delete_own_message', 'chat.upload_file', 'chat.download_file', 'chat.pin_message',
            'monitoring.access', 'monitoring.view_overview', 'monitoring.view_live_employees',
            'monitoring.view_team_activity', 'monitoring.view_applications',
            'monitoring.view_screenshots', 'monitoring.view_reports',
        ],
        'accountant' => [
            'dashboard.view', 'employees.view', 'payroll.*', 'salary.*',
            'payslips.*', 'loans.*', 'advances.*', 'overtime.view',
            'reports.view', 'reports.export', 'notifications.view',
            'chat.access', 'chat.direct_message', 'chat.join_public_channel',
            'chat.post_message', 'chat.edit_own_message', 'chat.delete_own_message',
            'chat.upload_file', 'chat.download_file',
        ],
        'employee' => [
            'dashboard.view',
            'notifications.view',
            'attendance.view',
            'leave.view',
            'leave.create',
            'payslips.view',
            'documents.view',
            'loans.view',
            'advances.view',
            'overtime.view',
            'announcements.view',
            'chat.access',
            'chat.direct_message',
            'chat.join_public_channel',
            'chat.post_message',
            'chat.edit_own_message',
            'chat.delete_own_message',
            'chat.upload_file',
            'chat.download_file',
            // Work monitoring is admin-only; employees have no monitoring.* permissions.
        ],
    ],
];
